@host = localhost:8080

// Access a Secured API Endpoint
GET http://{{host}}/api/secured/ping HTTP/1.1
content-type: application/json
authorization:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1kaW5oQGdvLmNvbSIsImV4cCI6MTcxNDE2ODEzOX0.D8SrskM9q9R5gN2_hMIc2OJxjHfOW5eVx6And2fmA-I"
###